name: uncertainty
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip=23.3.1
  - jupyter=1.0.0
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scipy=1.13.0
  - pip:
      - future==1.0.0
      - uncertainties==3.1.7